artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/banti9021/Life-Span-Of-Animals-Data-Prediction/raw/refs/heads/main/archive%20(16).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
